version: '3'
services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: digitalocean.com/php
        container_name: AtekCCS
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: AtekCCS
            SERVICE_TAGS: dev
        working_dir: /var/www
        networks:
            - app-network

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "90:90"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
